### ISSUE TITLE
Core-Swarm-Meeting - Thursday, 5th August 2021 - 17:00 to 19:00 UTC

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#105]
## Core Swarm Meeting -Thursday, 5th August 2021 - 17:00 to 19:00

- Last Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/102
- Next Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/119

### Moderator
- [x] JakobD

### Attendees
Checked Names confirmed as Attendees.
- [x] DominikTilman
- [x] FelixWeber
- [x] Filip
- [x] Tevo 
- [x] Seomon 
- [x] Victor Corcini

### Documentation
- [x] @stephen-rowan

## Agenda for today:
- [x] Check-Up
- [x] ATH Feedback
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/104
- No timer. The gaming room did not happen ? We only played Jackbox. - Seomon
- Timer on Miro Board is better solution. Have seperate gaming room - Seomon
- Announce ETH and Gaming TH on ATH Slides - Felix
- Revise design of  ATH Slides - Felix / Jacob
- Blockchain room was valuable - insights on DID - good that Robert O'Brien was there, We should record next time.  - Jacob / Filip
- Charles Hoskinson will attend next Town Hall - Felix
- Mini-Proposal workshop was quite a success and we should repeat it - Tevo
- We need one Miro account -  Tevo
- We should put more effort into Discord for feedback - Filip
- [x] Bridge Fund Distribution
- To keep it simple. 
- We have tracked in detail - Filip
- We can send surplus payment to treasury - Filip
- Motivate people going forward - Dominic
- We need rules for using treasury - Jacob / Filip
-  Make final decision when money is paid - Jacob / Filip / Dominik
- [x] Fund 6 Proposal
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/80
-  ATH Proposal - Filip
- Focus on After Town Hall activity and emphasize swarm network - Filip / Stephen
- Add Encourage entrepreneurs KPI
- Keep in mind referrer program - Jacob / Tevo
- [x] Hackathon Update
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/101
- We cannot use next ATH for the Hackathon - Jacob
- Start using breakout rooms for participants - Jacob
- Unclear use of virtual environment - Boone / Felix
- [x] Catalyst Swarm Website
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/99
- Setup website - Simon
- Text content - Related to our Fund 6 proposals - Dominic / Filip
- Meeting on a weekly basis to organize website - some monthly expense 60 euros - Seomon / Felix
- Domain ideas - catalyst-swarm.io , the-swarm.io , swarm-rocks.io, catalystswarm.com
- [x] Saturday Swarm Session
- Announce Holiday Edition for 7th August 2021 and return to normal afterwards.

## List of Open Agenda Items

List of Open Agenda Items - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues?q=is%3Aissue+is%3Aopen+label%3A%22Agenda+Item%22

**Comment by Sapereaude7** [comment]
Agenda for today:
Check-Up
ATH Feedback
Bridge Fund Distribution
Fund 6 Proposal
Hackathon Update
Catalyst Website

**Comment by stephen-rowan** [comment]
> 
> 
> Agenda for today:
> Check-Up
> ATH Feedback
> Bridge Fund Distribution
> Fund 6 Proposal
> Hackathon Update
> Catalyst Website

Agenda copied to main body and linked to related issues.
