### ISSUE TITLE
Core-Swarm-Meeting - Monday, 9th August 2021 - 17:00 UTC

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#119]
## Core Swarm Meeting -  Monday, 9th August 2021 - 17:00 UTC
- Last Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/105
- Next Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/131

### Moderator
- [x] JakobD

### Attendees
Checked Names confirmed as Attendees.
- [x] DominikTilman
- [x] FelixWeber
- [x] Filip
- [x] Tevo 
- [x] Seomon 

### Documentation
- [x] @stephen-rowan

### Agenda for today:
- [x] Check-Up - Congrats to all fund 5 winners!
- [x] Swarm Session Feedback
- [x] Boone / Hackathon - Friday 13th
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/120
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/126
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/121
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/52

- 4 participants derived from survey to pitch at ATH Breakout room on Wednesday 11th August 2021

- [x] ATH Organization
https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/118
-  Moderator - Jacob
- Sala de Cafe "Guía de Project Catalyst"
- WADA / Gimbalabs - James / Mercy
- Proposal Q & A - Dominik
- Proposer circle - Randall
- Catalyst Governance - Johnathan / Nori
- Mini Proposal Circle - Tevo / Stephen 
- Introduction to Catalyst - Victor / Seomon

- [x] ATH  Perspective on the numbers

- [x] Fund 6 Proposal Draft
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/80
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/62

- [x] Tracking
- After Town Hall tracking
- Insights from Zoom  - talk to IOG to get numbers

## Agenda Items

List of Open Agenda Items - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues?q=is%3Aissue+is%3Aopen+label%3A%22Agenda+Item%22

**Comment by Sapereaude7** [comment]
Agenda for today:
Check-Up - Congrats to all fund 5 winners!
Swarm Session Feedback
Boone / Hackathon - Friday 13th
ATH Organization + Perspective on the numbers
Fund 6 Proposal Draft
Tracking

**Comment by stephen-rowan** [comment]
> 
> 
> Agenda for today:
> Check-Up - Congrats to all fund 5 winners!
> Swarm Session Feedback
> Boone / Hackathon - Friday 13th
> ATH Organization + Perspective on the numbers
> Fund 6 Proposal Draft
> Tracking

Transferred Agenda to main body of issue.
