### ISSUE TITLE
Core Swarm Activities -  Monday 23rd, August 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#159]
## Core Swarm Activities -  Monday 23rd, August 2021

- Previous Day - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/157
- Next Day - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/160

This Issue is intended as a daily record of Core Swarm Activities. It includes a checklist of who contributed to Core Swarm on this day and a "Today's Activities" section where links to this day's major events and tasks can be linked.

This approach is still a work in progress and is intended as a prototype for tracking Core Swarm

## Today's Contributors ?
Checked Names confirmed as contributors.

- [ ] DominikTilman
- [x] FelixWeber
- [x] Filip
- [ ] JakobD
- [ ] Tevo 
- [ ] Victor Corcini
- [x] Seomon 

## Documentation
- [x] @stephen-rowan

## Today's Activities

- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/156
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/63

**Comment by FelixfromSwarm** [comment]
Call with Jack at 4am UTC ( https://www.youtube.com/channel/UCUl0e1S_69nW2EBAi_xlpxA ) to discuss potential partnership for Yûmi and Swarm in regard to video editing services and stuff

**Comment by FelixfromSwarm** [comment]
Adjusting some stuff on the website http://catalystswarm.com/

**Comment by FelixfromSwarm** [comment]
coordination with Mercy (WADA) for https://cardano.ideascale.com/a/dtd/Infrastructure-Devt-=-Access-Africa/367618-48088

**Comment by FelixfromSwarm** [comment]
starting to track some swarm only related stuff on github XD
