### ISSUE TITLE
Core-Swarm-Meeting -  IDEA FEST Planning for FUND 6/7 - 24th August 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#161]
## Core-Swarm-Meeting -  IDEA FEST Planning for FUND 6/7 - 24th August 2021

- Last Meeting - link to last meeting Issue

### Attendees
Checked Names confirmed as Attendees.
- [x] JakobD
- [x] DominikTilman
- [x] Filip

### Documentation

- [x] @stephen-rowan

## Notes
- https://cardano.ideascale.com/a/dtd/Fund-7-IDEA-FEST/366717-48088
- Finance part was difficult - Filip
- Process of Ideation was time-consuming for first Idea Fest - Dominik
- time for presentation can be reduced - Jakob
- 15 breakout rooms - 6 pitches - Dominik
- We submit for Fund 6 and 7 - Filip
- We are limited to 100 proposals max - Filip
- 100 proposals is already very much - Dominik
- Co-insides with Cardano Summit - Dominik
- Highlight Videos should be for everyone - Dominik
- All videos uploaded to IOG - but Swarm uploads voted proposals to Swam YouTube - Filip
- Get Cardano Youtube influencers to profile voted proposals - (Big Pey, Rick McCracken, Kaizen) - Dominik
- Community filters proposals for Cardano Youtube influencers - providing interesting content - Jakob
## Actions
- Speak to Rick McCracken about involvement in Idea Fest - Filip
- Update proposal to Fund 6 and 7 - Dominik
- Meeting 10UTC - Wednesday, 25th August 2021 to develop proposal further - Dominik / Filip

**Comment by dominiktilman** [comment]
Stefan will be Moderator again
