### ISSUE TITLE
Core-Swarm-Meeting - 30th August 2021, 15:00 UTC

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#171]
## Core-Swarm-Meeting - 30th August 2021, 15:00 UTC
[![Zoom Meeting Badge](https://img.shields.io/badge/Meeting-Zoom-blue)](https://us02web.zoom.us/j/81132158682)

- Previous Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/168
- Next Meeting  -

## Attendees
- [x] DominikTilman
- [x] FelixWeber
- [x] Filip
- [x] JakobD
- [x] Tevo 
- [x] Victor Corcini
- [x] Seomon 

## Documentation
- [x] @stephen-rowan

### WADA event on weekend
- Attended Saturday - Fiip / Stephen
- 20 people in WADA CA breakout room - Victor

### ATH Planning Wednesday
- https://docs.google.com/spreadsheets/d/1l1-jkdG9ybzhfR0liubpFK8MFRHEOE5N/edit#gid=1824093933

Facilitator | Co-Host | Date | Room name
-- | -- | -- | --
Jakob |   | 01.09.2021 | Moderator
-- | -- | -- | --
Dominik |   | 01.09.2021 | Feedback-Round for CA Tutorial
SofiH |   | 01.09.2021 | Challenge Setting Alignment session
Filip |   | 01.09.2021 | Blockademia verification system
Phil K |   | 01.09.2021 | Proposal promotion
Felix |   | 01.09.2021 | CC Facilitator Candidates
Victor | Lucio | 01.09.2021 | How to be a CA ( Catalyst School )
Liese | Anna | 01.09.2021 | Stadt nach Acht & Frei(T)râume
Tevo | Stephen W | 01.09.2021 | Mini-proposal workshop

### Cohort Reporting - Stephen & Jakob
- Funded cohort reporting is currently bi-weekly and based on public achievements. 
- Tracking the metrics in our proposals
- Not getting funding - how this impacts Swarms activities - discuss in Swarm Session - Felix
- Meeting Friday 3rd September 2021 13:00 UTC Friday to discuss Proposal Commitments - DominikTilman. Filip, JakobD, stephen-rowan et al.
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/173

### Internal organization: Enspiral Update?

- Focus on building team and relations not specifics - Filip
- Now has a Catalyst Project - DLT Toolbox Proposal - Filip
- Hailey Cooperrider - https://cardano.ideascale.com/a/dtd/Custom-game-to-improve-teamwork/369006-48088
- Main topics organization and invoicing - look at open collective - Filip

## Website
- Minor changes to color scheme and text content - Filip, Dominik, Simon

## Today's Activities

- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/171
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/64
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/172

**Comment by Sapereaude7** [comment]
Agenda for today:

Check-Up / Introduction - How is everyone doing?
WADA event on weekend
ATH Planning Wednesday
Cohort Reporting - Stephen & Jakob
Meeting for internal & external reporting relating to proposals
Internal organization: Enspiral Update?
