### ISSUE TITLE
Core Swarm Activities - Friday, 3rd September, 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#178]
## Core Swarm Activities - Friday, 3rd September, 2021

- Previous Day - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/177
- Next Day - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/181

This Issue is intended as a daily record of Core Swarm Activities. It includes a checklist of who contributed to Core Swarm on this day and a "Today's Activities" section where links to this day's major events and tasks can be linked.

This approach is still a work in progress and is intended as a prototype for tracking Core Swarm

## Today's Contributors ?
Checked Names confirmed as contributors.

- [x] DominikTilman
- [x] FelixWeber
- [x] Filip
- [x] JakobD
- [ ] Tevo 
- [ ] Victor Corcino
- [x] Seomon 

## Documentation
- [x] @stephen-rowan

## Today's Activities

- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/179
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/173
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/65
- https://github.com/Quality-Assurance-DAO/F6-Catalyst-value-onboarding-Catalyst-Swarm-Genesis-GitBook/issues/5

**Comment by FelixfromSwarm** [comment]
Organisation for Swarm Session
-inviting people
- DM on Discord with newcomers.. what the swarm is about

**Comment by FelixfromSwarm** [comment]
Meeting with @dominiktilman for Swarm Proposal budgets at 12.00 UTC

**Comment by FelixfromSwarm** [comment]
Preparing Swarm Session brekout room slides 
https://docs.google.com/presentation/d/1OvOIwbhVjhwPNodyJK9dkJV4666kg_2b4Ts032OmLGM/edit?usp=sharing

**Comment by FelixfromSwarm** [comment]
reaching out to Idea Fest hosts with @dominiktilman 
https://docs.google.com/spreadsheets/d/1O9o-JwLgbto1dJi_uIsp8LGQB796K2FEUGeY0VxmK6M/edit?usp=sharing

**Comment by dominiktilman** [comment]
-Reaching out to Hosts for IDEA FEST
-Sending confirmation Email to registered proposers of IDEA FEST
-Preparing slide for budget calculation for ATH, Swarm and IDEA FEST proposal
-Meeting with Stephen and Felix to discuss budget for proposals
-Tweet about Idea Fest
-Contacting Patrick Tobler for NFT-collaboration for Idea Fest

**Comment by FilipBl4gojevic** [comment]
- Meeting about tracking with Jakob, Simon, Felix, Stephen
- Main core meeting

**Comment by Sapereaude7** [comment]
-Meeting about tracking with Filip, Simon, Felix, Stephen
-Main Core Meeting, Moderation / Agenda preperation
-Reddit Post about Idea Fest
-Twitter Posts for Swarm
