### ISSUE TITLE
Core-Swarm-Meeting - Friday, 3rd September, 2021 - 15:00 UTC

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#179]
## Core-Swarm-Meeting - Friday, 3rd September, 2021 - 15:00 UTC
[![Zoom Meeting Badge](https://img.shields.io/badge/Meeting-Zoom-blue)](https://us02web.zoom.us/j/81132158682)

- Last Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/171
- Next Meeting - 

### Moderator
- [x] JakobD

### Attendees
Checked Names confirmed as Attendees.

- [x] DominikTilman
- [x] FelixWeber
- [x] Filip
- [ ] Tevo 
- [ ] Victor Corcini
- [x] Seomon 

### Documentation

- [x] @stephen-rowan

### Regular GitHub Review Meetings
- @stephen-rowan and @Seomon4u to hold regular Friday meetings at 12:00 UTC

### Proposal Update by Dominik
- Budget reduced for Swarm proposals - because of competition and we do not want to dominate each challenges treasury
- Aim to get foot in the door - Dominik
- Aim to get funded and gain a good reputation - Felix
- Idea Fest will be more fully funded to cover costs - Dominik
- Will be easier in our own challenge in Fund 7 - Dominik
- Do not think our reputation will be harmed by taking a percentage of treasury - Filip
- One wallet for each proposal - Dominik
- Applied for ADA Handle - Jakob - https://adahandle.com/

### Swarm Session tomorrow
- Mentor CAs in Swarm

Facilitator | Co-Host | Date | Room name | |
-- | -- | -- | -- | --
Felix |   | 04.09.2021 | Moderator |  
Filip |   | 04.09.2021 | Blockademia Verification System |  
Dominik | Stephen | 04.09.2021 | How to be Ca | CA - Workshop
Jakob | Tevo | 04.09.2021 | Q&A for CAs (After CA Workshop) |  
Felix |   | 04.09.2021 | Catalyst Intro | Covering Project Catalyst in a general discussion
Randall |   | 04.09.2021 | Proposal promotion |  

### Expenses reminder + Questions regarding the sheet
- Send 5.8 ADA to Felix - All

### Core Swarm Tracking

- JakobD — Today at 2:30 PM
> Hey everyone verybody today in the call, we that is Filip FelixWeber stephen.rowan Seomon and JakobD agreed that from now on, everybody is accountable to report very shortly on the daily github activities what they have been doing for the Swarm on that day. Everything else that is not recorded does not count. It is not perfect but will give us a first basis that we can build upon. Please all give a thumbs up to this message to show that you agree with this decision. Thus we can move forward with more clarity. Much love, Jakob

### Brainstorming meetup regarding future Swarm directions (tokenomics, corporation, whitepaper etc.)
- Set a meeting / workshop to discuss ?
- Head off competition from others who will introduce tokenomics - Felix
- What can be done to structure Swarm as a DAO, Stakepool etc
- Earlier discussion with Fiip touched on utility tokens - which relates to what each of us can provide as a service - Felix
- Each member to consider what they can provide as a service - All
- Google doc to discuss options - All

- Meeting to discuss future Swarm directions - Monday, 6th September 2021

**Comment by Sapereaude7** [comment]
Agenda for today:

Check-Up - How is everybody doing
New commitment: writing daily tasks on github
Proposal Update by Dominik
Swarm Session tomorrow
Expenses reminder + Questions regarding the sheet
Brainstorming meetup regarding future Swarm directions (tokenomics, corporation, whitepaper etc.)
