### ISSUE TITLE
Core Swarm Activities - Saturday, 4th September, 2021

### ISSUE THREAD

**Issue by whitevo** [Catalyst-Swarm/Catalyst-Beehive#180]
## Core Swarm Activities - [Date]

- Previous Day - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/178
- Next Day - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/184

This Issue is intended as a daily record of Core Swarm Activities. It includes a checklist of who contributed to Core Swarm on this day and a "Today's Activities" section where links to this day's major events and tasks can be linked.

This approach is still a work in progress and is intended as a prototype for tracking Core Swarm

## Today's Contributors ?
Checked Names confirmed as contributors.

- [x] DominikTilman
- [x] FelixWeber
- [x] Filip
- [ ] JakobD
- [x] Tevo 
- [x] Victor Corcini
- [ ] Seomon 

## Documentation
- [x] @stephen-rowan

## Today's Activities
- https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/48
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/182

**Comment by whitevo** [comment]
Updated Public Swarm session board.
https://miro.com/app/board/o9J_lzGHByg=/

**Comment by FelixfromSwarm** [comment]
Starting to coordinate Eastern Town Hall Idea Fest Fund 6 in ETH Organisation meeting at 8am UTC

- asking IOG to send out a mail to all proposers, asking proposer from Indonesia, Vietnam and Japan to resond to the mail to track local community proposer/proposals
- reaching out to local community hosts
- discussing required budget

**Comment by FelixfromSwarm** [comment]
Meeting with @whitevo, brainstorming about first ideas for Swarm utility tokens ( 16.00 to 17.30 CEST )

**Comment by FelixfromSwarm** [comment]
Swarm Session, Saturday September 4th at 17.00 UTC #182 

@FelixfromSwarm 
Moderating and introduce mainroom
hosting breakout room - Catalyst Introduction
setting up the Zoom breakout room
setting up the co-hosts

@dominiktilman @Sapereaude7 @whitevo @victorcorcino 
Hosting the Catalyst School - CA Workshop

@FilipBl4gojevic 
Hosting - Blockademia verification system

**Comment by stephen-rowan** [comment]
## Stephen Workflow
### Eastern Hemisphere Meeting - Saturday 4th September 08:00 to 11:00 UTC - took rough notes
https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/48

### Saturday Swarm Session - Saturday, 4th September 2021, 17:00 UTC  Co-Host with dominik
https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/182

**Comment by FilipBl4gojevic** [comment]
- Swarm session moderation - Blockademia

**Comment by dominiktilman** [comment]
- Sending out IDEA FEST registration confirmation to new sign-ups
- Talking to Patrick Tobler about NFT-Awards for IDEA FEST

**Comment by victorcorcino** [comment]
Presented Catalyst Short Intro before the CA Workshop
Hosted one of the Q&A rooms after the CA Workshop
