### ISSUE TITLE
Core-Swarm-Meeting - 6th September 2021, 15:00 UTC

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#186]
## Core-Swarm-Meeting - 6th September 2021, 15:00 UTC
[![Zoom Meeting Badge](https://img.shields.io/badge/Meeting-Zoom-blue)](https://us02web.zoom.us/j/81132158682)

- Last Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/179

### Moderator
- [x] JakobD

### Attendees
Checked Names confirmed as Attendees.

- [x] DominikTilman
- [x] FelixWeber
- [x] Tevo 
- [x] Victor Corcini
- [x] Seomon 

### Apologies
- [x] Filip

### Documentation

- [x] @stephen-rowan

## Agenda for today:
- [x] Check-Up
- [x] CA-Workshop Recap
- 80 % gave 5 stars
- 15 % gave 4 stars
- 45 people
![2021-09-06](https://user-images.githubusercontent.com/25156451/132237457-ca168372-648c-457d-b4a5-b435dd90f512.png)

![2021-09-06 (1)](https://user-images.githubusercontent.com/25156451/132237581-f96102a1-d609-4194-b733-79f4e2100e4b.png)

![2021-09-06 (2)](https://user-images.githubusercontent.com/25156451/132237708-6fcc8b83-0108-4ada-ac30-f40ddf16d2fc.png)

- [x] Guidelines needed for ATH and Swarm Breakout rooms
- People who want rooms should be aware of Host guidelines - DominikTilman
- Workflow for breakout room requests - Stephen
- Would be good to have voting - token - reputation system for rooms - Felix
- How to handle in short term - Jakob
- Do we need guidelines for how, who and when they can request a room - Stephen
- Contact Swarm to request Breakout room - no permanent rooms - think in advance what room people want - Jakob
- Since last week amount rooms increased - so we need to introduce some limits - DominikTilman
- Set a timeline when we need to set limits - Tevo
- Leave it open and see who turns up - Victor
- 3 days in advance send description of what room what they want - every host records session and provides feedback - Felix
- Announcing all breakout rooms - 3 days before - particularity for Saturday Swarm Sessions - Victor
- Make short video to pitch - Saturday Swarm Session - Felix
- Same procedure for room requests as ATH as Saturday Swarm - Jakob
- Announce we are expecting descriptions - Tevo
- If you want a breakout room send us a title, description - 250 char - Jakob
- title - max 15 characters - Felix
- Set up a Google Form - Jakob

- [x] On Chain voting for Circle
- Candidate could talk about themselves in mini proposal - Victor
- We could make a snapshot of all wallets - Tevo
- Circle time period coincides with fund - Felix
- Multiple proposals may be a problem - Victor
- On chain votes we do not have to use wallets - just IDs on Ideascale - Felix
- Catalyst Circle Version 2 - November 2021 to January 2022 - Stephen

## After Townhall Pipeline

Jakob |   | 08.09.2021 | Moderator
-- | -- | -- | --
Juan, Ayax, Roberto |   | 08.09.2021 | Sala de Cafe "Guía de Project Catalyst"
Hailey |   | 08.09.2021 | Gameful teambuilding
Tevo |  | 08.09.2021 | Mini-proposal workshop
Melanie Russo | Nori | 08.09.2021 | Grow Cardano Sustainability Challenge Team
Felix |   | 08.09.2021 | CC Secretary Candidates
Phil K |   | 08.09.2021 | Proposal promotion
Allison, David, Tim, |   | 08.09.2022 | Sustainable Funding Mechanisms
SPOCRA |   | 08.09.2021 | SPO room
Liese | Ana | 08.09.2021 | Berlin culture & Catalyst
Randall |   | 08.09.2021 | Smart Contract Safety - Labeling and Transparency
Victor |   | 08.09.2021 | How to be a CA ( Catalyst School )

**Comment by Sapereaude7** [comment]
Agenda for today:

Check-Up
CA-Workshop Recap
ATH this week
Proposal Finalization
