### ISSUE TITLE
Core-Swarm-Meeting - Friday, 10th September 2021, 16:00 UTC

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#197]
## Core-Swarm-Meeting - Friday, 10th September 2021, 16:00 UTC
[![Zoom Meeting Badge](https://img.shields.io/badge/Meeting-Zoom-blue)](https://us02web.zoom.us/j/81132158682)

- Last Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/186
- Next Meeting -

### Moderator
- [ ] JakobD

### Attendees
Checked Names confirmed as Attendees.

- [ ] DominikTilman
- [ ] FelixWeber
- [ ] Filip
- [ ] Tevo 
- [x] Victor Corcini
- [ ] Seomon 

### Documentation
- [x] @stephen-rowan

## Agenda Items
https://docs.google.com/spreadsheets/d/1vnGFw-SipQVJYb0Hz274wTci37srjytF/edit#gid=1824093933

### Saturday Swarm Session 
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/199
- Community Rewarding system - Felix
- Future of Swarm - Reputation and Tokenomics - Atala Prism - Jakob / Stephen
- Use of Meetup for Zoom links - Felix
- https://www.meetup.com/Catalyst-Swarm-Sessions/events/wmlmpsyccmbpb/
- Post Swarm Sessions on Thursday 

-- | -- | -- | -- | --
-- | -- | -- | -- | --
Victor | Tevo | 11.09.2021 | How to be a CA |  
Felix |   | 11.09.2021 | Community Rewarding system | Currently, the Catalyst Community does not have the possibility to track and reward engagement. What can a first draft look like ?
Jakob | Stephen | 11.09.2021 | Future of Swarm: Reputation System | Possible PRISM integration and giving tokens to people who join meets
Melanie | Simon | 11.09.2022 | Climate Change |  

#### Miro Board
https://miro.com/app/board/o9J_lxx7AQw=/

### AOB
- Jakob to introduce all Breakout rooms on ATH 
- Takes too much time for participants to introduce

**Comment by victorcorcino** [comment]
Attending to core meeting
Assigning myself responsibilities for IdeaFest in Fund6
