### ISSUE TITLE
Core-Swarm-Meeting - Monday, 13th September 2021- 15:00 UTC

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#202]
## Core-Swarm-Meeting - Monday, 13th September 2021- 15:00 UTC
[![Zoom Meeting Badge](https://img.shields.io/badge/Meeting-Zoom-blue)](https://us02web.zoom.us/j/81132158682)

- Last Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/197
- Next Meeting - 

### Moderator
- [x] JakobD

### Attendees
Checked Names confirmed as Attendees.

- [ ] DominikTilman
- [ ] FelixWeber
- [ ] Filip
- [ ] Tevo 
- [ ] Victor Corcini
- [ ] Seomon 

### Documentation

- [x] @stephen-rowan

###  ATH
- Secretary and Facilitators - post in Telegram about open space room
- approach circle members to attend - Felix

Jakob |   | 15.09.2021 | Moderator |  
-- | -- | -- | -- | --
Darlington |   | 15.09.2021 | LIDO Nation & Catalyst Review Tool | Cardano Community Reviews is an initiative to bring the core of the Catalyst Community Advisor process to the wider ecosystem and create a guard at search engines for newcomers.
Prasad | Marlene, Tevo, Victor | 15.09.2021 | Chainvote - Governance Application | Current application features include voting on elections and proposals
Victor | Chris | 15.09.2021 | vCA Workshop |  
Nfol | Nori, Stephen W, Juliana | 15.09.2021 | Catalyst Circle feedback | What should be allowed, what should not be allowed
Juan, Ayax, Roberto |   | 15.09.2021 | Sala de Cafe "Guía de Project Catalyst" |  
Melanie | Simon | 15.09.2021 | Climate Change |  
Umed |   | 15.09.2021 | Alonzo |  

### Zoom Account Access for Swarm Meetings
- We need shared account or own Zoom account - Jakob
- Create new Zoom account with Swarm account - Victor
- $169 per month - Zoom license - 10 licenses - Felix
- Lot of costs going out - no income coming in - Stephen
- Up to 4 licenses - 34 Euros - Jakob
- Another reason to upgrade account is limited to 100 participants - Felix
- Feel disappointed that IOHK have not paid - Simon
- I can setup 2 licences - cover costs and get refund later - Filip
- Share between 8 people = $ 21
- Only solution I see: I create zoom account for coreswarm and Felix has to create all the events with that account. - Tevo
- For me it is about increasing monthly costs - I currently pay $78 in advance each month and wait a month to get remittance (still not paid for August). I think we should setup a crowdfund and ask the community to contribute. - Stephen
- Feel like putting a lot in and not getting much out - Felix
- we our entrepreneurs starting our journey here, there is no stability - Stephen
- My proposals : Circle oversight 7.4k, Swarm, Gitbook , 3.4k, Open Source Training (School) 8.7k, Distributed Auditability (using Swarm as a pilot) 8.7k - Stephen
- If everything split equally - no incentive for new members - Jakob
- Everyone on core swarm should be able to sign up on Zoom - Felix

### Meeting with Kaizen
- 8pm UST - Felix / Jakob -

**Comment by Sapereaude7** [comment]
Further Agenda:
Zoom Account Access for Swarm Meetings
Meeting with Kaizen
