### ISSUE TITLE
After Town Hall - 15th September 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#205]
# After Town Hall - 15th September 2021

- [ ] Prepare Townhall room suggestions and host
- [ ] Town Hall Topics ?

# Breakout Sessions

Jakob |   | 15.09.2021 | Moderator
-- | -- | -- | --
Darlington |   | 15.09.2021 | LIDO Nation & Catalyst Review Tool
~~Prasad~~  | ~~Tevo~~ | ~~15.09.2021~~ | ~~Chainvote - Governance Application~~ 
Victor | Kriss | 15.09.2021 | vCA Workshop
Nori | Stephen W, Juliane | 15.09.2021 | Catalyst Circle feedback
Roberto | Juan, Ayax | 15.09.2021 | Sala de Cafe "Guía de Project Catalyst"
Melanie | Simon | 15.09.2021 | Climate Change
Umed |   | 15.09.2021 | Alonzo Era
Dan | Dan & Luca (SecretDecks) | 15.09.2021 | Catalyst DisCo - Distributed Co-Operatives

## Moderator Checklist for sessions

- Give co-host access to all the facilitators.
- Describe what is this event about
- Explain the process how event will be carried through
- Give voice to facilitators to allow them invite people to their room
- Suggest using collective Miro Board

## Host Checklist for sessions

- The host or co-host should assert the main subject over anyone who misdirects the session.
- Before each session a host should have prepared some content or know what they intend to present.
- Some preparation always helps
- When the session starts the host should ask if the attendees mind being recorded.
- The host should record the session (if there are no objections).
- The host or co-host should take notes of the session.

**Comment by whitevo** [comment]
Would be possible to postpone the Chainvote breakout room?
