### ISSUE TITLE
Create a folder with files or direct link to sources

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#21]
## Create a folder with files or direct link to sources

- [ ]  Create a folder with files or direct link to sources and/or gitlab link for Zoom guides for the tools we use. @whitevo ( Discord https://discordapp.com/channels/856453826060091422/859114652364177429/863286611037650944 )

**Comment by whitevo** [comment]
I think the Miro will solve this problem.
Just need this group agreement to attach the links to final version

**Comment by stephen-rowan** [comment]
I agree - but it would also be good to document the completed file structure in a Google Document.
