### ISSUE TITLE
Core Swarm Activities -  Wednesday, 22nd September

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#215]
## Core Swarm Activities -  Wednesday, 22nd September 2021

- Previous Day - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/214
- Next Day -

This Issue is intended as a daily record of Core Swarm Activities. It includes a checklist of who contributed to Core Swarm on this day and a "Today's Activities" section where links to this day's major events and tasks can be linked.

This approach is still a work in progress and is intended as a prototype for tracking Core Swarm

## Today's Contributors ?
Checked Names confirmed as contributors.

- [x] DominikTilman
- [ ] FelixWeber
- [ ] Filip
- [x] JakobD
- [x] Tevo 
- [ ] Victor Corcini
- [ ] Seomon 

## Documentation
- [x] @stephen-rowan

## Today's Activities

- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/216

**Comment by dominiktilman** [comment]
Idea Fest registration email
Storyboard for Swarm Trailer

**Comment by victorcorcino** [comment]
Review of assessments for ATH proposal with @Sapereaude7 and @dominiktilman

**Comment by whitevo** [comment]
Improved Swarm Stage Miro Board template.
Prepared Miro board for the new session.
