### ISSUE TITLE
Core Swarm Activities -  Friday, 1st October 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#240]
## Core Swarm Activities -  Friday, 1st October 2021

- Previous Day - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/239
- Next Day - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/242

This Issue is intended as a daily record of Core Swarm Activities. It includes a checklist of who contributed to Core Swarm on this day and a "Today's Activities" section where links to this day's major events and tasks can be linked.

This approach is still a work in progress and is intended as a prototype for tracking Core Swarm

## Today's Contributors ?
Checked Names confirmed as contributors.

- [ ] DominikTilman
- [x] FelixWeber
- [ ] Filip
- [ ] JakobD
- [ ] Tevo 
- [ ] Victor Corcini
- [ ] Seomon 

## Documentation
- [x] @stephen-rowan

## Today's Activities

- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/241

**Comment by FelixfromSwarm** [comment]
first  Idea Fest host onboarding session at 9am UTC with @dominiktilman & @FelixfromSwarm

**Comment by FelixfromSwarm** [comment]
Finished all organizing stuff for Eastern Idea Fest
https://www.meetup.com/Cardano-Catalyst-Community-Network/events/rwbvpsyccnbdb/

**Comment by FelixfromSwarm** [comment]
Starting to boost all the Events out ( Discord & Telegram )
Updating Meet up Events

**Comment by FelixfromSwarm** [comment]
Core meeting.
Sheduling meeting in Barcelon from November 25th to 29th
@Sapereaude7 taking care to find location (Airbnb)

**Comment by FelixfromSwarm** [comment]
2nd Idea Fest onboarding meeting done
