### ISSUE TITLE
Core-Swarm-Meeting - Friday, 1st October 2021 - 1500 UTC

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#241]
## Core-Swarm-Meeting - Friday, 1st October 2021 - 1500 UTC
[![Zoom Meeting Badge](https://img.shields.io/badge/Meeting-Zoom-blue)](https://us02web.zoom.us/j/81132158682)

![2021-10-01 (1)](https://user-images.githubusercontent.com/25156451/135648944-1696ab68-a8a7-43d2-8163-e641818f482f.png)

- Last Core Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/222
- Next Core Meeting - 

## Moderator
- [x] JakobD

## Attendees
Checked Names confirmed as Attendees.

- [x] DominikTilman
- [x] FelixWeber
- [x] Filip
- [x] Tevo 
- [x] Victor Corcini
- [x] Seomon 

## Documentation

- [x] @stephen-rowan

##Agenda for today:
### Check-Up
- Victor invading Europe in December 2021 - Lisbon - Barcelona...
- Thursday 25th to Monday 29th November 2021

### Swarm Summit
- Swarm Summit in Feb 2022 ? - Felix
- Sponsored by Cardano Foundation
- Cover flights to summit for low financial resources
- Charter or bulk deals - Hotels bookings - Sponsorships - etc
- Involve Space of Urgency
- Not only presentations 

### Ideafest for tomorrow - Checkmark
- Jakob in charge of voting so needs to be informed of changes to room sheet - Jakob / Dominik

### No Swarm Session tomorrow, right?
- Cancel Swarm Session

### Expenses reminder
- Swarm members to send payment to treasury on the 1st of every month - Victor
-

**Comment by Sapereaude7** [comment]
Agenda for today:
Check-Up
Ideafest for tomorrow - Checkmark
Upcoming Community Summit?
No Swarm Session tomorrow, right?
Expenses reminder
