### ISSUE TITLE
Core Swarm Activities - Saturday, 2nd October 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#242]
## Core Swarm Activities - Saturday, 2nd October 2021

- Previous Day - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/240
- Next Day - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/244

This Issue is intended as a daily record of Core Swarm Activities. It includes a checklist of who contributed to Core Swarm on this day and a "Today's Activities" section where links to this day's major events and tasks can be linked.

This approach is still a work in progress and is intended as a prototype for tracking Core Swarm

## Today's Contributors ?
Checked Names confirmed as contributors.

- [ ] DominikTilman
- [x] FelixWeber
- [ ] Filip
- [ ] JakobD
- [ ] Tevo 
- [ ] Victor Corcini
- [ ] Seomon 

## Documentation
- [x] @stephen-rowan

## Today's Activities

- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/243

**Comment by FelixfromSwarm** [comment]
Last updates on Idea Fest Fund 6 - Virtual Backrounds for Zoom

VB 1 New
![VB1 Min](https://user-images.githubusercontent.com/87385188/135707005-61f8d9bf-af5b-4ad9-84d7-2d70fb688d7b.png)


VB 2 New
![VB 2 New](https://user-images.githubusercontent.com/87385188/135707015-fc5a440a-2124-46c9-8721-11bcb16aa5c3.png)


VB 3 New
![VB3 New](https://user-images.githubusercontent.com/87385188/135707022-2560af54-b802-48ff-8a6e-f95bd03f5421.png)

**Comment by victorcorcino** [comment]
IdeaFest hosting

**Comment by FelixfromSwarm** [comment]
Idea Fest Hosting..
Succesfully executing Idea Fest with Team

Last updates and announcements via Discord and Meetup
Opening the Zoom Call
last Host & Special guest Introductions & checks
Setting up Breakout Rooms

Setting up gdrive folders for recordings

Fixing Zoom account issues in event beginning
