### ISSUE TITLE
Core-Swarm-Meeting - 4th October 2021 - 1500 UTC

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#247]
## Core-Swarm-Meeting - 4th October 2021 - 1500 UTC
[![Zoom Meeting Badge](https://img.shields.io/badge/Meeting-Zoom-blue)](https://us02web.zoom.us/j/81132158682)

- Last Meeting - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/241
- Next Meeting - 

### Moderator
- [x] JakobD

### Attendees
Checked Names confirmed as Attendees.

- [x] DominikTilman
- [x] FelixWeber
- [x] Filip
- [x] Tevo 
- [x] Victor Corcini
- [x] Seomon 

### Documentation

- [x] @stephen-rowan

### Review Ideafest Fund 6
- 83 proposals - 200 people - in both ETH and TH - Felix
- Corrupt recording from Randall - Tevo
- Idea Fest Documentation - https://catalyst-swarm.gitbook.io/catalyst-swarm-genesis/october-2021/idea-fest-2 - Stephen
- Lucio to add video presentation to Voter tool - Felix
- Announce voting next few days - Patrick to mint NFTs - Felix / Dom / Jakob

### ATH Wednesday

Jakob |   |   | Moderator
-- | -- | -- | --
CC |   | 06.10.2021 | Retrospective Room - Proposer
CC |   | 06.10.2021 | Retrospective Room - Proposer
CC |   | 06.10.2021 | Retrospective Room - Proposer
Melanie Russo |   | 06.10.2021 | Climate Change
Tevo Saks |   | 06.10.2021 | Cardano Project Catalyst Discord
Juan, Roberto, Ayax? |   | 06.10.2021 | Sala de Cafe

### Expense Update Victor
- Victor will share exact amount in Core Swarm costs channel - Victor

**Comment by victorcorcino** [comment]
Cost update:

October payment:
Amount: 34.47940 ADA
Wallet address: addr1q9ymc4jsr2cu4uy8d3zvnlj7hv2jkr2lhdtwll7xt0ykhctyg9djnqlr7m2wr2sv7nnxkzhgv46wzc7h97m5e7sxy2pqwwxup4

-> When you are done, please send me the transaction ID
