### ISSUE TITLE
Week 47 - (Stephen) - Monday, November 22nd to Sunday November 28th, 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#328]
## Week 47 - (Stephen) - Monday, November 22nd to Sunday November 28th, 2021
https://www.epochconverter.com/weeks/2021
- Previous Week - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/326
- Next Week - https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/331

## Weekly record of Catalyst Activities
- [x] @stephen-rowan

### 1) Eastern Hemisphere Meeting - 22nd Nov 0800 to 0900 UTC
- https://github.com/C3ETH/Catalyst-Eastern-Hemisphere-Co-Ordination/issues/88

### 2) Auditability Challenge Team
- Member correspondence 

### 3) 141 SecretDecks Town Hall - 23rd November 2021
- https://github.com/SecretDecks/Documentation/issues/141

## Wednesday, November 24th
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/329

### 1) [F7P-1]: Penny Lane - Proposal
- https://cardano.ideascale.com/a/dtd/Penny-Lane-Liverpool-Philosophy-Hub/383504-48088
### 2) [F7P-5]: QA-DAO Transcription Service - Proposal
- https://cardano.ideascale.com/a/dtd/QA-DAO-Transcription-Service/383492-48088
### 3) [F7P-10]: Catalyst Challenges Hub - Proposal
- https://cardano.ideascale.com/a/dtd/Catalyst-Challenges-Hub/383377-48088

### 1) [QAD-24]: F5 QA-DAO - November KPI Report
- https://quality-assurance-dao.gitbook.io/quality-assurance-dao/f5-qa-dao/reporting#25th-november-2021-kpi-report

### 2) [CSGG-8]: Swarm GitBook - November KPI Report
- https://quality-assurance-dao.gitbook.io/quality-assurance-dao/f6-swarm-gitbook/reporting#25th-november-2021-kpi-report

### 3) [OST-4]: F6-Open-Source-Training-November-KPI-Report
- https://quality-assurance-dao.gitbook.io/quality-assurance-dao/f6-open-source-training/reporting#25th-november-2021-kpi-report

### 4) [DA-4]: Distributed-Auditability-November-2021-KPI- Report
- https://quality-assurance-dao.gitbook.io/quality-assurance-dao/f6-distributed-auditability/distributed-auditability#25th-november-2021-kpi-report

### 1) [F7P-10]: Catalyst Challenges Hub
- https://quality-assurance-dao.gitbook.io/catalyst-fund-7-challenges/
### 1) [F7P-10]: Catalyst Challenges Hub
- https://quality-assurance-dao.gitbook.io/catalyst-fund-7-challenges/
- https://github.com/Catalyst-Challenges/Catalyst-Challenges-Coordination/issues/1
### 2) Catalyst-Swarm GitHub
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/330
- https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/331
### 3) [F7P-10]: Catalyst Challenges Hub
- https://github.com/Catalyst-Challenges/Catalyst-Challenges-Coordination/issues/1

**Comment by RICCARDO-da-Vinci** [comment]
Hiya...trying to work out how Dominik is involved with this...I want to sponsor him !!  I guess I am trying to see what work he has contributed...Ciao for now - Riccardo
