### ISSUE TITLE
Action Item : Slowly getting in touch with github

### ISSUE THREAD

**Issue by FelixfromSwarm** [Catalyst-Swarm/Catalyst-Beehive#37]
## Action Item : Slowly getting in touch with github

Decided to start tracking Swarm Core activities in GitHub.

- [x] All Core members need to create GitHub account.

## Current core members:

- [x]  Dominik Tilman @dominiktilman
- [x]   Felix Weber @FelixfromSwarm 
- [x]  Filip Blagojevic @FilipBl4gojevic 
- [x]  Jakob Dickhaut
- [x]  Simon Fleck @Seomon4u 
- [x]  Tevo Saks @whitevo 
- [x]  Victor Corcino @victorcorcino

## Curator & GitHub educator 

@stephen-rowan 

This issue will be solved when all current core members joined this issue

**Comment by dominiktilman** [comment]
Have a github account as well

**Comment by stephen-rowan** [comment]
I have sent an invite to be a member of this Catalyst-Beehive repo to @dominiktilman

S
