### ISSUE TITLE
Design Core Swarm Google Drive on Miro Board

### ISSUE THREAD

**Issue by whitevo** [Catalyst-Swarm/Catalyst-Beehive#38]
## Design Core Swarm Google Drive on Miro Board

Need to figure out better up to 3 layer architecture for Swarm google drive.
We are creating a lot of Documents and excel tools we can't find anymore and we have to start digging on different folders to find them.

- [x] Transparently show ideated changes for folder structure
- [x] Design the new look for the new Folder Structure
- [x] Showcase to team members and get change approval
- [x] Move files around
- [x] Load new file structure to the Miro Board
- [x] Check if more changes are needed

**Comment by whitevo** [comment]
Created a clean suggested version on Miro Board from the organizing ideas we did together with Seomon

**Comment by stephen-rowan** [comment]
@all-contributors please add @whitevo for Data

**Comment by Seomon4u** [comment]
@whitevo I am closing the issue since this has been done already.
