### ISSUE TITLE
Agenda Item : We should experiment with doing a Swarm session using Google Meet

### ISSUE THREAD

**Issue by whitevo** [Catalyst-Swarm/Catalyst-Beehive#40]
## Agenda Item : We should experiment with doing a Swarm session using Google Meet

We tried it for the first Easter Hemisphere Townhall meeting.
For me, it was a great experience.
Worth trying it out for Swarm session and then hold voting how users liked it compared to Zoom meeting,

**Comment by FelixfromSwarm** [comment]
well than e have the same problem we discussed already.
When we use different formats in different events, will be creating chaos only

**Comment by whitevo** [comment]
We change it all out if we find out it's better.
I have forgotten the reason we thought the transition is not worth testing.
Is there nothing we wanted to improve what Google meet has?

**Comment by FelixfromSwarm** [comment]
Hmmm
think the only advantages of Google meet is the facility to link all into a google acc.
