### ISSUE TITLE
Contacting Enspiral for organizational advice

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#44]
## Contacting Enspiral for organizational advice

> What’s your ‘meaningful work’ to do in the world?
https://www.enspiral.com/

**Comment by FilipBl4gojevic** [comment]
Sent an email, waiting for the response

**Comment by FilipBl4gojevic** [comment]
In communication with Enspiral, hopefully a meeting will happen in the week of August 9th-15th
