### ISSUE TITLE
Action Item : GitHub Training Core Swarm Members - Tuesday, 20th July 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#45]
## Action Item : GitHub Training Core Swarm Members - Tuesday, 20th July 2021

Available between 11:00 to 16:00 UTC ?
Please put your preferred time in the comments

## GitHub Training 10:00 to 11:00 UTC

- [x]  GitHub Training 10:00 to 11:00 UTC - @dominiktilman, @FelixfromSwarm, @FilipBl4gojevic 
- [x] Record Training for @Sapereaude7 (JacobD)
https://discord.com/channels/856453826060091422/857173182971904001/867006057129967616

## GitHub Training 15:00 to 16:00 UTC

- [x] GitHub Training 15:00 to 16:00 UTC - @Seomon4u , @whitevo, @victorcorcino
Unable to Record Training for @Sapereaude7 (JacobD)

#### How to Use GitHub for Automated Kanban Project Management
https://www.youtube.com/watch?v=YVFa5VljCDY

Good brief overview in the beginning - development oriented towards the end.

#### GitHub Project Management Tutorial - Setup GitHub Projects & Automations
https://www.youtube.com/watch?v=ff5cBkPg-bQ&t=1s

Comprehensive introduction to setting up project boards.

### GitHub: tasks, labels & milestones
https://www.youtube.com/watch?v=ukYSRu4k0gs

Basic project management with GitHub using task lists, labels and milestones.

**Comment by Seomon4u** [comment]
for me best would be **13UTC to 16UTC** but I could change my schedule if we can't find a common time in that timeframe.

**Comment by whitevo** [comment]
Starting from 15:00 UTC works for me

**Comment by FilipBl4gojevic** [comment]
**13 UTC** to **16 UTC** is best for me

**Comment by victorcorcino** [comment]
13 to 16 UTC works for me. Question: how long is it going to be?

**Comment by stephen-rowan** [comment]
Reply to https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/45#issuecomment-882778957

One hour maximum - @victorcorcino

**Comment by FelixfromSwarm** [comment]
13 to 16 fits for me as well

**Comment by FilipBl4gojevic** [comment]
I will join @dominiktilman at 10 UTC, @stephen-rowan please send link

**Comment by stephen-rowan** [comment]
Responding to https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/45#issuecomment-883238058

OK - @FilipBl4gojevic - I will post Zoom link in GitHub channel

**Comment by FelixfromSwarm** [comment]
Going to join at 10.00 UTC as well

**Comment by FelixfromSwarm** [comment]
@stephen-rowan @FilipBl4gojevic @dominiktilman 
We can use the Core Meeting call room which we use usually

**Comment by stephen-rowan** [comment]
Reply to https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/45#issuecomment-883252255

Cool @FelixfromSwarm - that would be better for recording
