### ISSUE TITLE
Agenda Item : Roles and Responsibilities

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#46]
## Agenda Item : Roles and Responsibilities

We need to be serious about commitment

After trail week of using GitHub 
Return to review of roles and Responsibilities on Core Swarm Meeting - Monday, 26th July 2021

**Comment by whitevo** [comment]
So @victorcorcino and Mike missing before we can close this agenda?

**Comment by stephen-rowan** [comment]
Look like it - needs their feedback before closing the Issue ?

**Comment by whitevo** [comment]
well, their roles were not disccussed like ours were.

**Comment by Sapereaude7** [comment]
True, on Friday victor can maybe elaborate on it a bit and then we'll close it. Mike is currently not involved anymore as I understood it. Or is that wrong?

**Comment by stephen-rowan** [comment]
Issue resolved by meeting https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/102
