### ISSUE TITLE
After Town Hall - 21st July 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#49]
## After Town Hall - 21st July 2021

- [x] Moderation - @Sapereaude7 - Jacob D

## Breakout Rooms

- [x] Sala de Cafe "Guía de Project Catalyst" | (Spanish Circle - Ayax, Roberto)
- [x] Catalyst School | Helping people to find way into the project and Q&A @Seomon4u 
- [x] Toolmaker and Maintainer Catalyst Circle - @FelixfromSwarm 
- [x] Catalyst Circles - Lauris Steglics
- [x]  Live voting on proposals | We use the Voting tool to randomly pick proposals and start voting on the proposals - @whitevo , @FilipBl4gojevic 

###  Miro Board
https://miro.com/app/board/o9J_l5oK3HM=/

**Comment by Sapereaude7** [comment]
The Other Catalyst Circles should be renamed in Catalyst Circles, they will be moderated by Lauris Steglics

**Comment by stephen-rowan** [comment]
## Feedback - Catalyst School | Helping people to find way into the project and Q&A @Seomon4u

- The host or co-host should assert the main subject over anyone who misdirects the session.
- Before each session a host should have prepared some content or know what they intend to present.
- When the session starts the host should ask if the attendees mind being recorded.
- The host should record the session (if there are no objections).
- The host should end the recording after the session times out (45 minutes).
