### ISSUE TITLE
Set up ADA Makerspace Hackathon

### ISSUE THREAD

**Issue by dominiktilman** [Catalyst-Swarm/Catalyst-Beehive#52]
![Header_4](https://user-images.githubusercontent.com/80850851/126310548-d1f10bf6-2b48-4d24-a170-33e01f5fd3d3.jpeg)
## Set up ADA Makerspace Hackathon

@whitevo
( https://discord.com/channels/856453826060091422/856453826932768770/866763001196576790)

- [x] prepare excels (from the data, aka I don't want to collect data, but I can help brainstorm what to collect and why)
- [x] Join the workshops and take notes.
- [x] Help to organize collective voting system (if we have that) + Analyze the results and create charts.
- [x]  could take speaker role, if I dont have to prepare for this and its something natural for me, but idk what that could be

@FelixfromSwarm 
(https://discord.com/channels/856453826060091422/856453826932768770/866764388412948530)
- [x] I would take charge of the project engine line just before the Hackathon to mobilize a community stream to participate
- [x] as well doing some stuff around ( finding some sponsors and collaborators )

**Comment by stephen-rowan** [comment]
Left a comment

**Comment by dominiktilman** [comment]
![Header_4](https://user-images.githubusercontent.com/80850851/126310548-d1f10bf6-2b48-4d24-a170-33e01f5fd3d3.jpeg)

**Comment by FelixfromSwarm** [comment]
Nice

**Comment by whitevo** [comment]
The explanation for my tasks since it caused questions.
These tasks are a list of things that I am willing to do. I don't take initiative, give me a date and time.

@Sapereaude7 was also interested to help with the hackathon that way.
Let him know the time and date when a specific thing is being discussed.

**Comment by stephen-rowan** [comment]
@whitevo - you should be able to edit the main body of this Issue yourself to refine your tasks and add date references.
- Milestone dates are set at the Issue level (e.g. one due date per issue).
- We can also break down the list above into separate issues (each with its own milestone). 
- If you hover your mouse over a checkbox - you can convert it into an issue,

**Comment by Seomon4u** [comment]
This event is over
