### ISSUE TITLE
Issue : Catalyst-Swarm-Genesis GitBook Scaleability 

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#6]
## Catalyst-Swarm-Genesis GitBook Scalability 

The way we use GitBook includes a lot of embedded media so is not typical.

- [x] Check Scalability of GitBook - numbers of concurrent users etc.

**Comment by whitevo** [comment]
Where we can measure how many website visits we have?
Because right now I don't see any issues with the loading.

I assume this is going to be an ongoing task if can't automate it by some measures?

**Comment by stephen-rowan** [comment]
Reply to https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/6#issuecomment-869773521

That is right - there are no short-term issues. Just something to keep an eye on because of the large amount of embedded content on the GitBook. Google analytics is available as an integration (https://docs.gitbook.com/integrations/google-analytics) - but I have no experience with that.

S

**Comment by stephen-rowan** [comment]
## Google Analytics

![2021-07-24 (1)](https://user-images.githubusercontent.com/25156451/126864649-f6dffc34-e99b-4b6d-8b0b-75f21042ccd5.png)

**Comment by Seomon4u** [comment]
no problems have risen so far, closing the issue therefore.
