### ISSUE TITLE
Fund 6 Proposal(s) Ideation

### ISSUE THREAD

**Issue by dominiktilman** [Catalyst-Swarm/Catalyst-Beehive#61]
## Fund 6 Proposal(s) Ideation

- [x] Select proposal(s) per challenge
- [x] Calculate amounts to cover our engagement
- [x] Write Proposals

**Comment by dominiktilman** [comment]
We have exactly 4 weeks until Fund6 submission phase begins. We should be ready to submit our proposals then. They don't have to be final (we have 3 more weeks for that) but they should be already professional ;)

**Comment by dominiktilman** [comment]
https://docs.google.com/document/d/1LKUFTDaJAdm3vkaozPGzFhtUQ05ERt16EI3gRk9Vwts/edit#

**Comment by FilipBl4gojevic** [comment]
@dominiktilman and me worked together on Swarm Sessions proposal, updated the Google doc, we will continue with other 2 proposals and have a discussion on Monday before the core meeting

**Comment by whitevo** [comment]
https://miro.com/app/board/o9J_l4nDsgw=/
Spread the document info around for the swarm part.
When skimming through the rest of the proposal I see that has a lot of repetition.
I propose to go through one proposal first before I prepare the 2nd one.

**Comment by dominiktilman** [comment]
https://docs.google.com/spreadsheets/d/1UpZ7ynUSiYxf_wI_89DDItXyIzLJevC_K7gNP5XCbis/edit?usp=sharing
