### ISSUE TITLE
Agenda Item - 31.07.2021 Make a game tournament in Swarm session 

### ISSUE THREAD

**Issue by whitevo** [Catalyst-Swarm/Catalyst-Beehive#76]
Jackbox, among us, townscare, etc

**Comment by Seomon4u** [comment]
I would love to play among us with you guys 
Not sure if its that great teambuilding tho 🗡️ :D

**Comment by stephen-rowan** [comment]
![2021-08-02 (14)](https://user-images.githubusercontent.com/25156451/127894332-b697a897-994a-4317-8992-cd9f909431d2.png)
