### ISSUE TITLE
Core Swarm Meeting - Monday, 26th July 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Beehive#78]
## Core Swarm Meeting - Monday, 26th July 2021- 16:30 UTC

- Last Meeting - Core Swarm Meeting - Friday, 23rd July 2021 https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/71

### Moderator
- [x] JakobD

### Attendees
Checked Names confirmed as Attendees.

- [x] DominikTilman
- [x] FelixWeber
- [x] Filip
- [x] Tevo 
- [x] Victor Corcini
- [x] Seomon 

### Documentation

- [x] @stephen-rowan

### Postponed
Peter from AdaTruth to attend Monday Meeting on to explain feedback on the timeliness of editing clips

### Meeting

- Open Agenda Items can be filtered using this link
https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues?q=is%3Aissue+is%3Aopen+label%3A%22Agenda+Item%22

### Agenda for today:

- [x] Warm-Up / Introduction
- [x] Set Up ADA Makerspace Hackathon
https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/52
- Set up meeting this week to plan event - Jacob D
- Assign responsibilities - Filip
- Set-up project - Felix / Tevo
- **Meeting - ADA Makerspace Hackathon - Thursday 29th July 19:30 UTC** - Tevo, Felix
- To figure out all the task list and how much time it will all take - then consult Boone - Tevo

- [x] Draft Swarm Fund 6 Proposals
https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/80
- Dominik and Filip to work together on draft proposals  - Dominik and Filip 
- Suggest using mini-proposal workshops to flesh out our Fund 6 Proposals - Tevo to liaise with Dominik and Filip 

- [x] ATH Organizing this week
- TH Topics - Jacob D to ask Dany
https://docs.google.com/spreadsheets/d/1l1-jkdG9ybzhfR0liubpFK8MFRHEOE5N/edit#gid=1824093933

![2021-07-26 (16)](https://user-images.githubusercontent.com/25156451/127033857-388192a8-6012-4c57-b0d3-5a364c702a6d.png)

- Media Rich NFT's - @Stack sophi	
- Mini Proposal Workshop - Tevo Saks / Stephen		
- Catalyst Circle	-  Victor 
- Challenge Setting Discussions	- Quasar	/ Sosha	
- T&M Problem sensing - 4	 - Felix Weber / Jon

- [x] Github-experiences 
- What good - not so good
- Any concerns ?
- More confident - more practice needed - The main core activities we can do - Filip
- I second Filip- no time - will be very effective for us - Victor
- It is a good tool - could be really valuable - a bit concerned that GitHuib can be overloaded - pair down redundant tasks - things can get lost in a lot of issues - Dominik
- Every month or two week to refresh GitHUb use - Stephen
- We need to refine GitHub email notifications - Tevo / Stephen

- [x] Roles & Responsibilities
https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/46

- I enjoy more organizational and technical subject. Helping with proposals .I can see taking responsibility in these areas. Possibly commit more time with funding- **Filip**
- Finance and accounting. Social Media and marketing strategy. Funding proposals. It makes less sense to take ownership of weekly events - **Dominik**
-  Automate and improve technical tools - time is limited - **Tevo** (Improving organizational structure, miro boards,  also session facilitation, website updates )
- Not so good at sessions, would like to work on GitHub, working on connected projects like Catalyst School, keeping track of structure, getting expertise together, networking .project management related stuff - **Simon**
- Link all my actions to Swarm, hard to define role - **Felix** (Filip - Felix is amazing at connecting with people and enjoys doing it)
(Force of nature - ever present and patient organizer - Stephen) (We do not have to call out specific roles - more about bringing out strengths - good at encouraging engagement with people - Jacob) ( I feel he is the CEO or master connector of Swarm - Felix)
- Documentation, technical project management support, tracking activities - **Stephen** - (Good at responding to questions - Tevo
- After Town Hall moderation - hosts, topics, core swarm moderation - Project management,  Hackathon- **Jacob** (I see you moving forward into governance and politics development - Felix)

- [x] Tokenomics - Dominic and Filip to talk to Gimbalabs - Stephen to collate various tokenomics sources 
-Felix we should observe what is going on

Less urgent:
- [ ] Maintaining Catalyst Swarm Discord Server Activity
https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/39
- [ ] Tokenomics with Pete
https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/79

- Model of distribution of funds to contributors

- [ ] Managing Agenda Items
https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/58
- [ ] Game Tournament Swarm Session
https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/76

**Comment by Sapereaude7** [comment]
Agenda for today:
Warm-Up / Introduction
Set Up ADA Makerspace Hackathon
Draft Swarm Fund 6 Proposals
ATH Organizing this week
Github-experiences + Roles & Responsibilities

Less urgent:
Maintaining Catalyst Swarm Discord Server Activity
Tocenomics with Pete
Managing Agenda Items
Game Tournament Swarm Session
