### ISSUE TITLE
Agenda Item - Million Money Monkey reward calculation

### ISSUE THREAD

**Issue by Seomon4u** [Catalyst-Swarm/Catalyst-Beehive#79]
## Million Money Monkey reward calculation

Oliver Krueger asked me if we would like to explore multiple ways of calculating rewards for the swarm, with one of them being his 'Million Money Monkey System' and another being our preferred way of calculating rewards like 'pie slice' for example.

He offered to do legwork for us in this context.

**Comment by whitevo** [comment]
This also relates to the tokenomic excel agenda.
https://github.com/Catalyst-Swarm/Catalyst-Beehive/issues/22
